// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHimECVVA2vVgcQFqz4Qxtlx3G78Tgw4U',
    appId: '1:497655411829:web:6302f3b4b192082127743c',
    messagingSenderId: '497655411829',
    projectId: 'smart-beauty-6c972',
    authDomain: 'smart-beauty-6c972.firebaseapp.com',
    storageBucket: 'smart-beauty-6c972.firebasestorage.app',
    measurementId: 'G-ERHV25TDWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1msl7OaPfCkfkAct_P2aal8KnYRc7okc',
    appId: '1:497655411829:android:63ca1b635c85d48b27743c',
    messagingSenderId: '497655411829',
    projectId: 'smart-beauty-6c972',
    storageBucket: 'smart-beauty-6c972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI39xZQJ-4KWrejncGbCEpdBWO1gTwseg',
    appId: '1:497655411829:ios:8352618f4bd4d45127743c',
    messagingSenderId: '497655411829',
    projectId: 'smart-beauty-6c972',
    storageBucket: 'smart-beauty-6c972.firebasestorage.app',
    iosBundleId: 'com.example.smartBeauty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI39xZQJ-4KWrejncGbCEpdBWO1gTwseg',
    appId: '1:497655411829:ios:8352618f4bd4d45127743c',
    messagingSenderId: '497655411829',
    projectId: 'smart-beauty-6c972',
    storageBucket: 'smart-beauty-6c972.firebasestorage.app',
    iosBundleId: 'com.example.smartBeauty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHimECVVA2vVgcQFqz4Qxtlx3G78Tgw4U',
    appId: '1:497655411829:web:d74175a15f97531427743c',
    messagingSenderId: '497655411829',
    projectId: 'smart-beauty-6c972',
    authDomain: 'smart-beauty-6c972.firebaseapp.com',
    storageBucket: 'smart-beauty-6c972.firebasestorage.app',
    measurementId: 'G-CVZEY5G99D',
  );
}
